title: timi was here # name of the site
author: Timotei Ciupei # name of site's author
email: timociupei@gmail.com # email of site's author
url: https://gandalf789.github.io/ # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
 "And I guess I just don't know" 

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "69420" # put your GoatCounter name if you want to use GoatCounter analytics


enable_google_verification: true
google_site_verification: L8RuFSNGvm3I7i2-Le81AIraftDHFEwcy4ll85hHTvQ  # your google-site-verification ID (Google Search Console) 
bing_site_verification:  # out your bing-site-verification ID (Bing Webmaster) 


# Google Analytics
google_analytics: G-ZCPKY3W09B

#theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "[<]" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

whitelist:
  - jekyll-feed
  - jekyll-seo-tag
